# Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9

    working_directory: ~/repo

    steps:
      - checkout

      # Already in npm build script :)
      # - run: git submodule update --init --recursive --remote

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: npm run-script build

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # deploy
      - deploy:
          name: "Publish Website"
          command: |
            if [ "${CIRCLE_BRANCH}" == "circle-ci" ]; then
              ls -lR dist
            fi


